# Generated by Django 4.2.3 on 2023-07-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_closing_time_doctor_opening_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='name',
        ),
    ]
