# Generated by Django 4.2.3 on 2023-07-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_doctor_image_doctor_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='closing_time_Mon_to_Fri',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='closing_time_Saturday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='closing_time_Sunday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='opening_time_Mon_to_Fri',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='opening_time_Saturday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='opening_time_Sunday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
