# Generated by Django 4.2.3 on 2023-07-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_facebook_account_doctor_google_plus_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='google_plus_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='twitter_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='youtube_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
