# Generated by Django 4.2.3 on 2023-07-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='year_of_completion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
