# Generated by Django 4.2.3 on 2023-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctor_institute_doctor_year_of_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='completion_year',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='year_of_completion',
        ),
        migrations.AddField(
            model_name='doctor',
            name='educations_and_degrees',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
