# Generated by Django 4.2.3 on 2023-07-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='gallery',
            field=models.ManyToManyField(to='department.gallery'),
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ImageField(default='', upload_to='department/gallary/'),
            preserve_default=False,
        ),
    ]
