# Generated by Django 4.2.3 on 2023-07-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_department_owner_alter_ownergallery_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
        migrations.RemoveField(
            model_name='department',
            name='owner',
        ),
        migrations.DeleteModel(
            name='OwnerGallery',
        ),
        migrations.AddField(
            model_name='department',
            name='images',
            field=models.ManyToManyField(blank=True, to='department.image'),
        ),
    ]
