# Generated by Django 4.2.3 on 2023-07-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_remove_department_images_department_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='departmentGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='department/gallary')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
