# Generated by Django 4.2.3 on 2023-07-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_department_description_departmentgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentgallery',
            options={'verbose_name': 'departmentgallery', 'verbose_name_plural': 'department gallery'},
        ),
    ]
