# Generated by Django 4.2.3 on 2023-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0014_department_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
